theme: jekyll-theme-cayman
title: ChatGPT Plus 升级教程 | 虚拟卡实测指南 | 野卡
description: 适合中国用户的 Plus 开通方法（虚拟卡、野卡、支付宝充值流程）
google_analytics: G-LC9J5G7XX4
url: "https://chatgpt-helper-tech.github.io"
baseurl: "chatgpt-plus-guide"
plugins:
  - jekyll-seo-tag
